name: GitHub Pages
on:
  schedule:
    - cron: '0 0,12 * * 1'
  workflow_dispatch:
jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        book: ['jungno', 'yeokhae']
    steps:
      - uses: actions/checkout@v2

      - name: chmod
        run: |
          chmod -v +x *.sh *.py

      - name: Download SDL
        run: |
         wget --no-clobber "https://raw.githubusercontent.com/${GITHUB_ACTOR:?Download whose copy of sdl}/sdl/main/sdl-requirements.txt" -O"/tmp/sdl-requirements.txt"
         pip install -r "/tmp/sdl-requirements.txt"
         wget --no-clobber "https://raw.githubusercontent.com/${GITHUB_ACTOR:?Download whose copy of sdl}/sdl/main/sdl.py" -O"/tmp/sdl.py"
         chmod -v +x "/tmp/sdl.py"

      - name: Download book
        run: |
          ./${{ matrix.book }}-dl.sh

      - name: Generate tables
        run: |
          pip install -r ${{ matrix.book }}-requirements.txt
          sed -E --in-place 's/; dragon.+//g' ${{ matrix.book }}.sh
          ./${{ matrix.book }}.sh

      - name: Push
        run: |
          git rm -rf .github *.sh *.py *-requirements.txt
          (git fetch --depth 1 origin gh-pages:gh-pages; git checkout gh-pages) || git checkout --orphan gh-pages
          cp -v /tmp/${{ matrix.book }}* .
          ls -lah
          git add ${{ matrix.book }}*
          git config user.email '-'
          git config user.name 'GitHub Actions'
          if [ -n $(git status --porcelain) ]
          then
            git commit -m 'Update'
            git push --set-upstream origin gh-pages
          fi
